services:
  app:
    image: anjoman:latest
    environment:
      - MONGO_URL=mongodb://mongodb:27017/anjoman
    volumes:
      - ./upload:/app/upload
  mongodb:
    image: mongo:5.0
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
  nginx:
    image: nginx:latest
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/peyvand.razaviedu.ir/:/etc/ssl/peyvand.razaviedu.ir/

  # portainer
  